table _Measures
	lineageTag: 3da1353c-5808-4000-bd85-75c575cfe368

	measure 'Acumulated Cases' = SUM(FactCovid[Accumulated Cases])
		formatString: 0
		displayFolder: Measures
		lineageTag: 5d2a902a-6ba8-4a38-baa0-95df1fd044b9

	measure 'New Cases' = SUM(FactCovid[Values])
		formatString: #,0
		displayFolder: Measures
		lineageTag: 3ef9dc80-1017-48b3-80f8-cac98d152a74

	measure 'Tooltip Title' = "Accumulated Cases - " & SELECTEDVALUE(DimCountry[Country])
		displayFolder: Titles
		lineageTag: 0ddb8834-1570-4e45-b40f-eb0553a453c3

	measure 'Cases MoM%' =
			
			VAR __PREV_MONTH = CALCULATE([New Cases], DATEADD('DimDate'[Date], -1, MONTH))
			RETURN
				DIVIDE([New Cases] - __PREV_MONTH, __PREV_MONTH, 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Measures
		lineageTag: 924a3fbd-90d4-4ba6-9d79-46e8760d8c78

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MonthOverMonth"
				}

		changedProperty = FormatString

	measure 'Maximum New Cases in 1 Day' = MAX(FactCovid[Values])
		formatString: 0
		displayFolder: Measures
		lineageTag: 3e1f1673-c104-4868-a2c7-018b69a27ba1

	column -
		dataType: string
		isHidden
		lineageTag: 05b13011-ef91-4aa6-8e5e-bfa66e6c5a75
		summarizeBy: none
		sourceColumn: -

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"-" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"-", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

