table _Measures
	lineageTag: 3da1353c-5808-4000-bd85-75c575cfe368

	measure TotalValue = SUM(FactCovid[Value])
		formatString: 0
		lineageTag: 5d2a902a-6ba8-4a38-baa0-95df1fd044b9

	measure TotalValuePD =
			
			VAR previous_day=PREVIOUSDAY(DimDate[FullDate])
			VAR result=CALCULATE([TotalValue], DimDate[FullDate]=previous_day)
			RETURN
			result
		formatString: 0
		lineageTag: 71a86696-71da-4d58-85d2-f833fa5aea4c

	measure NewCases = [TotalValue]-[TotalValuePD]
		formatString: 0
		lineageTag: 3ef9dc80-1017-48b3-80f8-cac98d152a74

	column -
		dataType: string
		lineageTag: 05b13011-ef91-4aa6-8e5e-bfa66e6c5a75
		summarizeBy: none
		sourceColumn: -

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"-" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"-", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

