table FactCovid
	excludeFromModelRefresh
	lineageTag: cbad25c5-add3-4ab7-ae2d-e0c06529353d

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 955f9d5f-2da9-4881-8438-e183079c8ad5
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column CountryKey
		dataType: int64
		formatString: 0
		lineageTag: 3d3fd1db-a81f-433b-a9dc-5646e22c5cbe
		summarizeBy: none
		sourceColumn: CountryKey

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Accumulated Cases'
		dataType: int64
		formatString: 0
		lineageTag: f6d4fce1-5001-44ea-97a5-4f691a27d293
		summarizeBy: none
		sourceColumn: Accumulated Cases

		annotation SummarizationSetBy = User

	column Column =
			
			VAR previous_day=PREVIOUSDAY(DimDate[Date])
			VAR ValuePD=CALCULATE([Acumulated Cases], DimDate[Date]=previous_day)
			VAR result=FactCovid[Accumulated Cases]-ValuePD
			RETURN
			result
		formatString: 0
		lineageTag: f53b5d05-3cf1-441e-b2eb-7b70e4784b5c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Values
		dataType: int64
		formatString: 0
		lineageTag: e2160d04-50bd-40fe-8ec7-975a9766e172
		summarizeBy: none
		sourceColumn: Values

		annotation SummarizationSetBy = User

	partition FactCovid = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(CleanSourceCovid, {"Country/Region"}, DimCountry, {"Country"}, "DimCountry", JoinKind.LeftOuter),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Attribute", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Attribute"}, DimDate, {"BadDate"}, "DimDate", JoinKind.LeftOuter),
				    #"Expanded DimCountry" = Table.ExpandTableColumn(#"Merged Queries", "DimCountry", {"CountryKey"}, {"CountryKey"}),
				    #"Sorted Rows1" = Table.Sort(#"Expanded DimCountry",{{"CountryKey", Order.Ascending}}),
				    #"Filtered Rows" = Table.SelectRows(#"Sorted Rows1", each [CountryKey] <> null),
				    #"Expanded DimDate" = Table.ExpandTableColumn(#"Filtered Rows", "DimDate", {"DateKey"}, {"DateKey"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded DimDate",{"DateKey", "CountryKey", "Country/Region", "Attribute", "Value"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"Attribute", "Country/Region"}),
				    #"Sorted Rows2" = Table.Sort(#"Removed Columns",{{"CountryKey", Order.Ascending}, {"DateKey", Order.Ascending}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Sorted Rows2",{"CountryKey", "DateKey", "Value"}),
				    #"Added Index" = Table.AddIndexColumn(#"Reordered Columns1", "Index", 0, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Index0"}}),
				    #"Added Index1" = Table.AddIndexColumn(#"Renamed Columns", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Index1",{{"Index", "Index1"}}),
				    #"Merged Queries1" = Table.NestedJoin(#"Renamed Columns1", {"Index0"}, #"Renamed Columns1", {"Index1"}, "Renamed Columns1", JoinKind.LeftOuter),
				    #"Expanded Renamed Columns1" = Table.ExpandTableColumn(#"Merged Queries1", "Renamed Columns1", {"Value"}, {"Renamed Columns1.Value"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded Renamed Columns1",{"Index0", "Index1"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns1",{{"Renamed Columns1.Value", "MovedValue"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns2", "NonAccumulatedValues", each if [DateKey]>1 then [Value]-[MovedValue] else [Value]),
				    #"Renamed Columns3" = Table.RenameColumns(#"Added Custom",{{"Value", "Accumulated Cases"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns3",{"MovedValue"}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Removed Columns2",{{"NonAccumulatedValues", "Values"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns4",{{"Values", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

