table FactCovid
	excludeFromModelRefresh
	lineageTag: cbad25c5-add3-4ab7-ae2d-e0c06529353d

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 955f9d5f-2da9-4881-8438-e183079c8ad5
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column CountryKey
		dataType: int64
		formatString: 0
		lineageTag: 3d3fd1db-a81f-433b-a9dc-5646e22c5cbe
		summarizeBy: none
		sourceColumn: CountryKey

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: f6d4fce1-5001-44ea-97a5-4f691a27d293
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = User

	column Column =
			
			VAR previous_day=PREVIOUSDAY(DimDate[Date])
			VAR ValuePD=CALCULATE([Acumulated Cases], DimDate[Date]=previous_day)
			VAR result=FactCovid[Value]-ValuePD
			RETURN
			result
		formatString: 0
		lineageTag: f53b5d05-3cf1-441e-b2eb-7b70e4784b5c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition FactCovid = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(CleanSourceCovid, {"Country/Region"}, DimCountry, {"Country"}, "DimCountry", JoinKind.LeftOuter),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Attribute", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Attribute"}, DimDate, {"BadDate"}, "DimDate", JoinKind.LeftOuter),
				    #"Expanded DimCountry" = Table.ExpandTableColumn(#"Merged Queries", "DimCountry", {"CountryKey"}, {"CountryKey"}),
				    #"Sorted Rows1" = Table.Sort(#"Expanded DimCountry",{{"CountryKey", Order.Ascending}}),
				    #"Filtered Rows" = Table.SelectRows(#"Sorted Rows1", each [CountryKey] <> null),
				    #"Expanded DimDate" = Table.ExpandTableColumn(#"Filtered Rows", "DimDate", {"DateKey"}, {"DateKey"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded DimDate",{"DateKey", "CountryKey", "Country/Region", "Attribute", "Value"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"Attribute", "Country/Region"}),
				    #"Sorted Rows2" = Table.Sort(#"Removed Columns",{{"CountryKey", Order.Ascending}, {"DateKey", Order.Ascending}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Sorted Rows2",{"CountryKey", "DateKey", "Value"})
				in
				    #"Reordered Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

